In [88]:
import pandas as pd
import numpy as np
from IPython import display
from matplotlib import image
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure
import ipywidgets as widgets
%matplotlib notebook
from ipywidgets import *


stationlocs = pd.read_csv("BARTLocationPercentages.csv")
print(stationlocs)

    Station_Name  X_Percentage  Y_Percentage  Rain_Critical  \
0    A50_TCR_105        51.968        57.745              1
1        A10_TCR        41.631        46.257              1
2        R60_TCR        24.080        13.060              1
3    R50_TCR_105        26.500        15.830              1
4        R10_TCR        36.250        26.480              1
..           ...           ...           ...            ...
295  E10-TEMPMON        67.665        11.020              0
296  E39-TEMPMON        80.000        11.000              0
297   C55-TC-UPS        56.917        11.881              0
298   E10-TC-UPS        67.665        11.020              0
299   NOAA_ALERT        11.000         6.000              0

           Asset_Location
0                Bay Fair
1            Lake Merritt
2                Richmond
3    El Cerrito Del Norte
4                   Ashby
..                    ...
295    Temperature Sensor
296    Temperature Sensor
297    Temperature Sensor
298    Temperature Sensor
299       Emergency Alert

[300 rows x 5 columns]

In [49]:
vizpic = display.Image("./BARTtracksmap.png")
picdata = image.imread('./BARTtracksmap.png')
#picdata

In [50]:
x = stationlocs['Station_Name'].tolist()

In [51]:
x

['A50_TCR_105',
 'A10_TCR',
 'R60_TCR',
 'R50_TCR_105',
 'R10_TCR',
 'M90_TCR_116A',
 'M90_TCR_114',
 'M90_TCR_113',
 'M90_TCR_112',
 'M10_TCR',
 'L30_TCR_108D',
 'K30_TCR',
 'C10_TCR',
 'A20_TCR_108',
 'A20_TCR_107',
 'C60_TCR',
 'C50_TCR_104',
 'Y10_TCR_B',
 'Y10_TCR_A',
 'Y10_TCR_552',
 'W40_TCR',
 'W40_TCR_103A',
 'W40_TCR_103',
 'W40_TCR_102',
 'W34_TCR',
 'W30_TCR',
 'W20_TCR_101',
 'W10_TCR_111E',
 'W10_TCR_110',
 'S50_TCR',
 'S44_TCH',
 'S40_TCR',
 'S28_TCH',
 'S26_TCH',
 'S24_TCH',
 'S20_TCR',
 'S12_TCR',
 'S06_TCR',
 'R40_TCR_105',
 'R30_TCR_110A',
 'R30_TCR_110',
 'R20_TCR_105C',
 'ORY_TCR_101',
 'M50_TCR_101D',
 'M40_TCR_106B',
 'M30_TCR_102D',
 'M20_TCR',
 'M16_TCR',
 'ODY_TCR_106',
 'M94_TCR_MSC',
 'M80_TCR_106',
 'M80_TCR_105',
 'M70_TCR_205',
 'M60_TCR_101D',
 'L20_TCR',
 'L18_TCR',
 'L16_TCR',
 'L14_TCR',
 'L10_TCR_102A',
 'L06_TCR',
 'C20_TCR',
 'C88_TCR',
 'C80_TCR',
 'C76_TCR',
 'C70_TCR_109',
 'OCY_TCR',
 'C54_TCR',
 'C40_TCR',
 'C30_TCR',
 'K20_TCR_213E',
 'K10_TCR_102B',
 'K10_TCR_101B',
 'K10_TCR_101',
 'A40_TCR',
 'A30_TCR_105A',
 'A90_TCR',
 'A80_TCR_101C',
 'A80_TCR_101',
 'A80_TCR_101B',
 'HTT_TCR',
 'OHY_TCR',
 'A70_TCR',
 'A60_TCR',
 'A58_TCR',
 'E30_TCR',
 'E10_TCR',
 'P-369',
 'P-333',
 'P-008',
 'A-351',
 'P-356',
 'P-363',
 'A-387',
 'P-341',
 'A-25',
 'P-375',
 'P-148',
 'P-018',
 'P-078',
 'P-188',
 'P-313',
 'P-062',
 'P-150',
 'P-183',
 'P-38',
 'P-215B',
 'P-174',
 'B-231',
 'P-216A',
 'P-179',
 'P-140',
 'P-55',
 'A-200',
 'A-266',
 'A-108',
 'P-142',
 'P-44',
 'P-288',
 'A-151',
 'P-112',
 'A-118_CL',
 'P-48',
 'A-99',
 'B-8',
 'A-55',
 'A-274',
 'P-236',
 'A-96_CL',
 'P-280',
 'P-153',
 'A-211',
 'B-305',
 'P-254',
 'P-190',
 'A-139',
 'P-31_RL',
 'A-861',
 'A-811',
 'A-868',
 'P-44_2',
 'P-2',
 'P-251',
 'P-788',
 'P-651',
 'P-304',
 'P-438',
 'P-729',
 'A-796',
 'P-809',
 'P-234',
 'P-154',
 'P-634',
 'P-835',
 'P-377',
 'P-900',
 'P-532',
 'P-73',
 'A50-TEMPMON',
 'A50-TC-UPS',
 'A10-TEMPMON',
 'A10-TC-UPS',
 'R60-TEMPMON',
 'R60-TC-UPS',
 'R50-TEMPMON',
 'R50-TC-UPS',
 'R10-TEMPMON',
 'R10-TC-UPS',
 'M90-TEMPMON',
 'M90-TC-UPS',
 'M10-TEMPMON',
 'M10-TC-UPS',
 'L30-TEMPMON',
 'L30-TC-UPS',
 'K30-TEMPMON',
 'K30-TC-UPS',
 'C10-TEMPMON',
 'C10-TC-UPS',
 'A20-TEMPMON',
 'A20-TC-UPS',
 'C60-TEMPMON',
 'C60-TC-UPS',
 'C50-TEMPMON',
 'C50-TC-UPS',
 'Y10-TEMPMON',
 'Y10-TC-UPS',
 'W40-TEMPMON',
 'W40-TC-UPS',
 'W34-TEMPMON',
 'W34-TC-UPS',
 'W30-TEMPMON',
 'W30-TC-UPS',
 'W20-TEMPMON',
 'W20-TC-UPS',
 'W10-TEMPMON',
 'W10-TC-UPS',
 'S50-TEMPMON',
 'S50-TC-UPS',
 'S44-TEMPMON',
 'S44-TC-UPS',
 'S40-TEMPMON',
 'S40-TC-UPS',
 'S28-TEMPMON',
 'S28-TC-UPS',
 'S26-TEMPMON',
 'S26-TC-UPS',
 'S24-TEMPMON',
 'S24-TC-UPS',
 'S20-TEMPMON',
 'S20-TC-UPS',
 'S12-TEMPMON',
 'S12-TC-UPS',
 'S06-TEMPMON',
 'S06-TC-UPS',
 'R40-TEMPMON',
 'R40-TC-UPS',
 'R30-TEMPMON',
 'R30-TC-UPS',
 'R20-TEMPMON',
 'R20-TC-UPS',
 'ORY-TEMPMON',
 'ORY-TC-UPS',
 'M50-TEMPMON',
 'M50-TC-UPS',
 'M40-TEMPMON',
 'M40-TC-UPS',
 'M30-TEMPMON',
 'M30-TC-UPS',
 'M20-TEMPMON',
 'M20-TC-UPS',
 'M16-TEMPMON',
 'M16-TC-UPS',
 'ODY-TEMPMON',
 'ODY-TC-UPS',
 'M94-TEMPMON',
 'M94-TC-UPS',
 'M80-TEMPMON',
 'M80-TC-UPS',
 'M70-TEMPMON',
 'M70-TC-UPS',
 'M60-TEMPMON',
 'M60-TC-UPS',
 'L20-TEMPMON',
 'L20-TC-UPS',
 'L18-TEMPMON',
 'L18-TC-UPS',
 'L16-TEMPMON',
 'L16-TC-UPS',
 'L14-TEMPMON',
 'L14-TC-UPS',
 'L10-TEMPMON',
 'L10-TC-UPS',
 'L06-TEMPMON',
 'L06-TC-UPS',
 'C20-TEMPMON',
 'C20-TC-UPS',
 'C88-TEMPMON',
 'C88-TC-UPS',
 'C80-TEMPMON',
 'C80-TC-UPS',
 'C76-TEMPMON',
 'C76-TC-UPS',
 'C70-TEMPMON',
 'C70-TC-UPS',
 'OCY-TEMPMON',
 'OCY-TC-UPS',
 'C54-TEMPMON',
 'C54-TC-UPS',
 'C40-TEMPMON',
 'C40-TC-UPS',
 'C30-TEMPMON',
 'C30-TC-UPS',
 'K20-TEMPMON',
 'K20-TC-UPS',
 'K10-TEMPMON',
 'K10-TC-UPS',
 'A40-TEMPMON',
 'A40-TC-UPS',
 'A30-TEMPMON',
 'A30-TC-UPS',
 'A90-TEMPMON',
 'A90-TC-UPS',
 'A80-TEMPMON',
 'A80-TC-UPS',
 'HTT-TEMPMON',
 'HTT-TC-UPS',
 'OHY-TEMPMON',
 'OHY-TC-UPS',
 'A70-TEMPMON',
 'A70-TC-UPS',
 'A60-TEMPMON',
 'A60-TC-UPS',
 'A58-TEMPMON',
 'A58-TC-UPS',
 'E30-TEMPMON',
 'E30-TC-UPS',
 'E10-TEMPMON',
 'E39-TEMPMON',
 'C55-TC-UPS',
 'E10-TC-UPS',
 'NOAA_ALERT']

In [52]:
y = 'M10'

In [53]:
y

'M10'

In [54]:
for i in x:
    if y in i:
        print(i)

M10_TCR
M10-TEMPMON
M10-TC-UPS

In [55]:
testlog = pd.read_csv("testocclog.csv")
print(testlog.columns)

Index(['Time', 'Ref', 'Log', 'BPD', 'Location'], dtype='object')

In [56]:
testlog = testlog.drop(columns=['BPD', 'Ref'])

In [57]:
print(testlog)

    Time                                                Log Location
0    622  DMZ1 issued Cat B W/O's for MW02 to set on and...      M60
1    640  DMZ1 cleared Cat B W/O's for the M1 Track and ...      M60
2    656  DMZ1 issued Cat B W/O's for the M55XL to crank...      M55
3    658  T950 Inspection train in C80 TM1 dispatching t...      C80
4    700  Single Tracking established on the M2 Track be...      M17
5    703  DMZ1 cleared Cat B W/O's for the M55XL. Protec...      M55
6    732  T918 completed track inspection on the C2 Trac...      C20
7    735  T229 verified A78[A1/A2] cranked, clamped and ...      A78
8    745  T918 completed track inspection on the C1 Trac...      K10
9    753                      T221 R60-2 No ATO doors, 311.      R60
10   753  T507 issued road manual into M40-2 and verifie...      M40
11   753                      T221 R60-2 No ATO doors, 311.      R60
12   753  A/L/S & R Line opened and staffed per SOFO.[Bu...      R10
13   756       C/K Line opened and staffed per SOFO.[Bucio]      C10
14   759                      T221 R50-2 No ATO doors, 311.      R50
15   801       M/W Line opened and staffed per SOFO[Bucio].      M10
16   802                      T221 R40-2 No ATO doors, 311.      R40
17   806  T221 R30-2 No ATO doors, 311. Tango advised Ro...      R30
18   809                       T221 R20- No ATO doors, 311.      R20
19   811                      T221 R10-2 No ATO doors, 311.      R10
20   815  OL05 issued Cat B W/O's for the M1 Track betwe...      M17
21   816  T221 late arrival to K30-2, forced meet with T...      K30
22   818  OL05 cleared Cat B W/O's for the M1 Track betw...      M17

In [58]:
stationarr = (stationlocs['Station_Name']).tolist()
sarr = []
for s in stationarr:
    s = s[0:3]
    sarr.append(s)

In [59]:
sarr

['A50',
 'A10',
 'R60',
 'R50',
 'R10',
 'M90',
 'M90',
 'M90',
 'M90',
 'M10',
 'L30',
 'K30',
 'C10',
 'A20',
 'A20',
 'C60',
 'C50',
 'Y10',
 'Y10',
 'Y10',
 'W40',
 'W40',
 'W40',
 'W40',
 'W34',
 'W30',
 'W20',
 'W10',
 'W10',
 'S50',
 'S44',
 'S40',
 'S28',
 'S26',
 'S24',
 'S20',
 'S12',
 'S06',
 'R40',
 'R30',
 'R30',
 'R20',
 'ORY',
 'M50',
 'M40',
 'M30',
 'M20',
 'M16',
 'ODY',
 'M94',
 'M80',
 'M80',
 'M70',
 'M60',
 'L20',
 'L18',
 'L16',
 'L14',
 'L10',
 'L06',
 'C20',
 'C88',
 'C80',
 'C76',
 'C70',
 'OCY',
 'C54',
 'C40',
 'C30',
 'K20',
 'K10',
 'K10',
 'K10',
 'A40',
 'A30',
 'A90',
 'A80',
 'A80',
 'A80',
 'HTT',
 'OHY',
 'A70',
 'A60',
 'A58',
 'E30',
 'E10',
 'P-3',
 'P-3',
 'P-0',
 'A-3',
 'P-3',
 'P-3',
 'A-3',
 'P-3',
 'A-2',
 'P-3',
 'P-1',
 'P-0',
 'P-0',
 'P-1',
 'P-3',
 'P-0',
 'P-1',
 'P-1',
 'P-3',
 'P-2',
 'P-1',
 'B-2',
 'P-2',
 'P-1',
 'P-1',
 'P-5',
 'A-2',
 'A-2',
 'A-1',
 'P-1',
 'P-4',
 'P-2',
 'A-1',
 'P-1',
 'A-1',
 'P-4',
 'A-9',
 'B-8',
 'A-5',
 'A-2',
 'P-2',
 'A-9',
 'P-2',
 'P-1',
 'A-2',
 'B-3',
 'P-2',
 'P-1',
 'A-1',
 'P-3',
 'A-8',
 'A-8',
 'A-8',
 'P-4',
 'P-2',
 'P-2',
 'P-7',
 'P-6',
 'P-3',
 'P-4',
 'P-7',
 'A-7',
 'P-8',
 'P-2',
 'P-1',
 'P-6',
 'P-8',
 'P-3',
 'P-9',
 'P-5',
 'P-7',
 'A50',
 'A50',
 'A10',
 'A10',
 'R60',
 'R60',
 'R50',
 'R50',
 'R10',
 'R10',
 'M90',
 'M90',
 'M10',
 'M10',
 'L30',
 'L30',
 'K30',
 'K30',
 'C10',
 'C10',
 'A20',
 'A20',
 'C60',
 'C60',
 'C50',
 'C50',
 'Y10',
 'Y10',
 'W40',
 'W40',
 'W34',
 'W34',
 'W30',
 'W30',
 'W20',
 'W20',
 'W10',
 'W10',
 'S50',
 'S50',
 'S44',
 'S44',
 'S40',
 'S40',
 'S28',
 'S28',
 'S26',
 'S26',
 'S24',
 'S24',
 'S20',
 'S20',
 'S12',
 'S12',
 'S06',
 'S06',
 'R40',
 'R40',
 'R30',
 'R30',
 'R20',
 'R20',
 'ORY',
 'ORY',
 'M50',
 'M50',
 'M40',
 'M40',
 'M30',
 'M30',
 'M20',
 'M20',
 'M16',
 'M16',
 'ODY',
 'ODY',
 'M94',
 'M94',
 'M80',
 'M80',
 'M70',
 'M70',
 'M60',
 'M60',
 'L20',
 'L20',
 'L18',
 'L18',
 'L16',
 'L16',
 'L14',
 'L14',
 'L10',
 'L10',
 'L06',
 'L06',
 'C20',
 'C20',
 'C88',
 'C88',
 'C80',
 'C80',
 'C76',
 'C76',
 'C70',
 'C70',
 'OCY',
 'OCY',
 'C54',
 'C54',
 'C40',
 'C40',
 'C30',
 'C30',
 'K20',
 'K20',
 'K10',
 'K10',
 'A40',
 'A40',
 'A30',
 'A30',
 'A90',
 'A90',
 'A80',
 'A80',
 'HTT',
 'HTT',
 'OHY',
 'OHY',
 'A70',
 'A70',
 'A60',
 'A60',
 'A58',
 'A58',
 'E30',
 'E30',
 'E10',
 'E39',
 'C55',
 'E10',
 'NOA']

In [60]:
stationlocs['Location'] = sarr

In [61]:
print(stationlocs)

    Station_Name  X_Percentage  Y_Percentage  Rain_Critical  \
0    A50_TCR_105        51.968        57.745              1
1        A10_TCR        41.631        46.257              1
2        R60_TCR        24.080        13.060              1
3    R50_TCR_105        26.500        15.830              1
4        R10_TCR        36.250        26.480              1
..           ...           ...           ...            ...
295  E10-TEMPMON        67.665        11.020              0
296  E39-TEMPMON        80.000        11.000              0
297   C55-TC-UPS        56.917        11.881              0
298   E10-TC-UPS        67.665        11.020              0
299   NOAA_ALERT        11.000         6.000              0

           Asset_Location Location
0                Bay Fair      A50
1            Lake Merritt      A10
2                Richmond      R60
3    El Cerrito Del Norte      R50
4                   Ashby      R10
..                    ...      ...
295    Temperature Sensor      E10
296    Temperature Sensor      E39
297    Temperature Sensor      C55
298    Temperature Sensor      E10
299       Emergency Alert      NOA

[300 rows x 6 columns]

In [62]:
justxandy = stationlocs.drop(columns=['Station_Name', 'Rain_Critical', 'Asset_Location'])

In [63]:
print(justxandy)

     X_Percentage  Y_Percentage Location
0          51.968        57.745      A50
1          41.631        46.257      A10
2          24.080        13.060      R60
3          26.500        15.830      R50
4          36.250        26.480      R10
..            ...           ...      ...
295        67.665        11.020      E10
296        80.000        11.000      E39
297        56.917        11.881      C55
298        67.665        11.020      E10
299        11.000         6.000      NOA

[300 rows x 3 columns]

In [64]:
merged = testlog.merge(justxandy.set_index('Location'), on='Location')

In [65]:
merged

,Time,Log,Location,X_Percentage,Y_Percentage
0,622,DMZ1 issued Cat B W/O's for MW02 to set on and...,M60,18.199,58.303
1,622,DMZ1 issued Cat B W/O's for MW02 to set on and...,M60,18.199,58.303
2,622,DMZ1 issued Cat B W/O's for MW02 to set on and...,M60,18.199,58.303
3,640,DMZ1 cleared Cat B W/O's for the M1 Track and ...,M60,18.199,58.303
4,640,DMZ1 cleared Cat B W/O's for the M1 Track and ...,M60,18.199,58.303
5,640,DMZ1 cleared Cat B W/O's for the M1 Track and ...,M60,18.199,58.303
6,658,T950 Inspection train in C80 TM1 dispatching t...,C80,66.134,11.020
7,658,T950 Inspection train in C80 TM1 dispatching t...,C80,66.134,11.020
8,658,T950 Inspection train in C80 TM1 dispatching t...,C80,66.134,11.020
9,732,T918 completed track inspection on the C2 Trac...,C20,44.152,23.910
10,732,T918 completed track inspection on the C2 Trac...,C20,44.152,23.910
11,732,T918 completed track inspection on the C2 Trac...,C20,44.152,23.910
12,745,T918 completed track inspection on the C1 Trac...,K10,38.815,38.337
13,745,T918 completed track inspection on the C1 Trac...,K10,38.800,38.365
14,745,T918 completed track inspection on the C1 Trac...,K10,38.807,38.340
15,745,T918 completed track inspection on the C1 Trac...,K10,38.815,38.337
16,745,T918 completed track inspection on the C1 Trac...,K10,38.815,38.337
17,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060
18,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060
19,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060
20,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060
21,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060
22,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060
23,753,T507 issued road manual into M40-2 and verifie...,M40,20.000,50.460
24,753,T507 issued road manual into M40-2 and verifie...,M40,20.000,50.460
25,753,T507 issued road manual into M40-2 and verifie...,M40,20.000,50.460
26,753,A/L/S & R Line opened and staffed per SOFO.[Bu...,R10,36.250,26.480
27,753,A/L/S & R Line opened and staffed per SOFO.[Bu...,R10,36.250,26.480
28,753,A/L/S & R Line opened and staffed per SOFO.[Bu...,R10,36.250,26.480
29,811,"T221 R10-2 No ATO doors, 311.",R10,36.250,26.480
30,811,"T221 R10-2 No ATO doors, 311.",R10,36.250,26.480
31,811,"T221 R10-2 No ATO doors, 311.",R10,36.250,26.480
32,756,C/K Line opened and staffed per SOFO.[Bucio],C10,41.697,26.541
33,756,C/K Line opened and staffed per SOFO.[Bucio],C10,41.697,26.541
34,756,C/K Line opened and staffed per SOFO.[Bucio],C10,41.697,26.541
35,759,"T221 R50-2 No ATO doors, 311.",R50,26.500,15.830
36,759,"T221 R50-2 No ATO doors, 311.",R50,26.500,15.830
37,759,"T221 R50-2 No ATO doors, 311.",R50,26.500,15.830
38,801,M/W Line opened and staffed per SOFO[Bucio].,M10,35.195,42.561
39,801,M/W Line opened and staffed per SOFO[Bucio].,M10,35.195,42.561
40,801,M/W Line opened and staffed per SOFO[Bucio].,M10,35.195,42.561
41,802,"T221 R40-2 No ATO doors, 311.",R40,28.896,18.405
42,802,"T221 R40-2 No ATO doors, 311.",R40,28.896,18.405
43,802,"T221 R40-2 No ATO doors, 311.",R40,28.896,18.405
44,806,"T221 R30-2 No ATO doors, 311. Tango advised Ro...",R30,31.330,21.110
45,806,"T221 R30-2 No ATO doors, 311. Tango advised Ro...",R30,31.330,21.110
46,806,"T221 R30-2 No ATO doors, 311. Tango advised Ro...",R30,31.330,21.110
47,806,"T221 R30-2 No ATO doors, 311. Tango advised Ro...",R30,31.330,21.110
48,809,"T221 R20- No ATO doors, 311.",R20,33.830,23.800
49,809,"T221 R20- No ATO doors, 311.",R20,33.830,23.800
50,809,"T221 R20- No ATO doors, 311.",R20,33.830,23.800
51,816,"T221 late arrival to K30-2, forced meet with T...",K30,38.908,32.784
52,816,"T221 late arrival to K30-2, forced meet with T...",K30,38.908,32.784
53,816,"T221 late arrival to K30-2, forced meet with T...",K30,38.908,32.784

In [66]:
merged['dupped'] = merged.duplicated(subset=['Log'])
merged = merged[merged.dupped != True]

In [67]:
merged

,Time,Log,Location,X_Percentage,Y_Percentage,dupped
0,622,DMZ1 issued Cat B W/O's for MW02 to set on and...,M60,18.199,58.303,False
3,640,DMZ1 cleared Cat B W/O's for the M1 Track and ...,M60,18.199,58.303,False
6,658,T950 Inspection train in C80 TM1 dispatching t...,C80,66.134,11.020,False
9,732,T918 completed track inspection on the C2 Trac...,C20,44.152,23.910,False
12,745,T918 completed track inspection on the C1 Trac...,K10,38.815,38.337,False
17,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060,False
23,753,T507 issued road manual into M40-2 and verifie...,M40,20.000,50.460,False
26,753,A/L/S & R Line opened and staffed per SOFO.[Bu...,R10,36.250,26.480,False
29,811,"T221 R10-2 No ATO doors, 311.",R10,36.250,26.480,False
32,756,C/K Line opened and staffed per SOFO.[Bucio],C10,41.697,26.541,False
35,759,"T221 R50-2 No ATO doors, 311.",R50,26.500,15.830,False
38,801,M/W Line opened and staffed per SOFO[Bucio].,M10,35.195,42.561,False
41,802,"T221 R40-2 No ATO doors, 311.",R40,28.896,18.405,False
44,806,"T221 R30-2 No ATO doors, 311. Tango advised Ro...",R30,31.330,21.110,False
48,809,"T221 R20- No ATO doors, 311.",R20,33.830,23.800,False
51,816,"T221 late arrival to K30-2, forced meet with T...",K30,38.908,32.784,False

In [71]:
vizdata = merged.drop(columns=['dupped'])

In [72]:
vizdata

,Time,Log,Location,X_Percentage,Y_Percentage
0,622,DMZ1 issued Cat B W/O's for MW02 to set on and...,M60,18.199,58.303
3,640,DMZ1 cleared Cat B W/O's for the M1 Track and ...,M60,18.199,58.303
6,658,T950 Inspection train in C80 TM1 dispatching t...,C80,66.134,11.020
9,732,T918 completed track inspection on the C2 Trac...,C20,44.152,23.910
12,745,T918 completed track inspection on the C1 Trac...,K10,38.815,38.337
17,753,"T221 R60-2 No ATO doors, 311.",R60,24.080,13.060
23,753,T507 issued road manual into M40-2 and verifie...,M40,20.000,50.460
26,753,A/L/S & R Line opened and staffed per SOFO.[Bu...,R10,36.250,26.480
29,811,"T221 R10-2 No ATO doors, 311.",R10,36.250,26.480
32,756,C/K Line opened and staffed per SOFO.[Bucio],C10,41.697,26.541
35,759,"T221 R50-2 No ATO doors, 311.",R50,26.500,15.830
38,801,M/W Line opened and staffed per SOFO[Bucio].,M10,35.195,42.561
41,802,"T221 R40-2 No ATO doors, 311.",R40,28.896,18.405
44,806,"T221 R30-2 No ATO doors, 311. Tango advised Ro...",R30,31.330,21.110
48,809,"T221 R20- No ATO doors, 311.",R20,33.830,23.800
51,816,"T221 late arrival to K30-2, forced meet with T...",K30,38.908,32.784

In [110]:
#vizpic


# fig = plt.figure(figsize=(8, 6), dpi=900) uncomment
# plt.imshow(picdata) uncomment



# size = fig.get_size_inches()*fig.dpi uncomment


# size in pixel
#plt.plot(1200* .18199, 1100 * .58303, marker='v', color="blue")
# print(size)
# print(size[0]* .18199)

#first get one dot superimposed based on percentages
#get all the dots on the picture
#make time attribute figure out time scroll (maybe ipywidgets)

#uncomment
# for index,row in vizdata.iterrows():
#     plt.plot(1200* (row['X_Percentage']/100), 1100 * (row['Y_Percentage']/100), marker='v', color="blue")



# plt.show()   uncomment

#x = np.linspace(0, 2 * np.pi)
# fig = plt.figure(figsize=(8, 6), dpi=150)
# plt.imshow(picdata)
# for index,row in vizdata.iterrows():
#     plt.plot(1200* (row['X_Percentage']/100), 1100 * (row['Y_Percentage']/100), marker='v', color="blue")


def update(time = 622):
    #line.set_ydata(np.sin(w * x))
    fig = plt.figure(figsize=(8, 6), dpi=150)
    plt.imshow(picdata)
    for index,row in vizdata.iterrows():
        if row['Time'] <= time:
            plt.plot(1200* (row['X_Percentage']/100), 1100 * (row['Y_Percentage']/100), marker='v', color="blue")
    fig.canvas.draw_idle()

#interact(update);
interact(update, time = widgets.IntSlider(value=622, min=500, max=1200, step=1));

interactive(children=(IntSlider(value=622, description='time', max=1200, min=500), Output()), _dom_classes=('w…

18.199
18.199
66.134
44.152
38.815
24.08
20.0
36.25
36.25
41.696999999999996
26.5
35.195
28.896
31.33
33.83
38.908